### ISSUE TITLE
Deprecated function cl.enqueue_read_buffer and misc.imread

### ISSUE THREAD

**Issue by honglin-c** [shapeforge/byextopopt#1]
Hello! This project is really cool and I was trying to run the code today. But I found the function `cl.enqueue_read_buffer` and `misc.imread` seemed to be deprecated in the following files:
https://github.com/shapeforge/byextopopt/blob/6e6098989ef63ae4bf76c8c465e126f02f90c592/src/appearance.py#L142-L143
https://github.com/shapeforge/byextopopt/blob/6e6098989ef63ae4bf76c8c465e126f02f90c592/src/images.py#L20
I tried replacing the `cl.enqueue_read_buffer` and `misc.imread` with `cl.enqueue_copy` and `imageio.imread` respectively in order to run the code. But then I will get the following error when optimizing over the appearance:
```
* ProblemType.AppearanceWithMaxCompliance
* Initial volume = 0.4
- Appearance = 0.000
- Compliance = 537.151
- Volume = 40.000 %
- Volume = 40.000 %
- Appearance = 0.000
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main(parse_args())
  File "main.py", line 53, in main
    (x_rgb_out, nelx_out, nely_out, results_out) = run(input_params)
  File "main.py", line 36, in run
    (x, nelx, nely, results) = multires.multires(params.nelx, params.nely, params, bc)
  File "/Users/honglin/projects/others/byextopopt/src/multires.py", line 37, in multires
    x = solver.optimize(x, enforce_constraints=(level > 0))
  File "/Users/honglin/projects/others/byextopopt/src/solver.py", line 206, in optimize
    x = self.opt.optimize(x)
  File "/Users/honglin/opt/anaconda3/lib/python3.8/site-packages/nlopt/nlopt.py", line 334, in optimize
    return _nlopt.opt_optimize(self, *args)
  File "/Users/honglin/projects/others/byextopopt/src/solver.py", line 226, in compliance_function
    self.problem.compute_displacements(self.x_phys)
  File "/Users/honglin/projects/others/byextopopt/src/topopt.py", line 108, in compute_displacements
    cvxopt.cholmod.linsolve(K, B)
ArithmeticError: 3688
```
I am kind of new to python and not sure what is going wrong here. Could you help me with this issue? Thank you! :)

**Comment by jdumas** [comment]
What platform are you testing on? I was able to run the code on a Windows machine with a Nvidia GPU using the following conda environment:

```yaml
name: byextopopt
channels:
  - conda-forge
dependencies:
  - python
  - cvxopt
  - nlopt=2.4.2
  - numpy
  - scipy=1.0.1
  - matplotlib
  - pyopencl=2018.1.1
  - decorator
  ```
  
However, when I tried on a Linux or macOS machine, I was not able to run it properly. Unfortunately the OpenCL part of this codebase is a bit finicky and may cause issues (such as NaN), but I don't have a good explanation for it :/

**Comment by honglin-c** [comment]
I was trying that on a macOS machine and I guess that is probably the problem. After setting up the conda environment, I also got NaN issues. :(
I will try it on a Windows machine next time. Thanks for the prompt reply! :)
